### ISSUE TITLE
[Grant Application]: Pizzap

### ISSUE THREAD

**Issue by Pizzap-io** [taikoxyz/grants#29]
### Project Description

Pizzap is a user-benefit-oriented and mass-adopted AI ecosystem. Members can create, show and trade NFTs in this community on Taiko Network. We will build the largest AI&NFT Dapp on Taiko Network at first, and will shock the whole web3 field.

### Category

NFT Bridge & Marketplace

### Timeline

Milestone1, 20 October 2023,  

- [ ] Support basic AIGC creation(text2img, text2voice)  when minting NFTs
- [ ] Support  NFTs(minted on Taikos Network) show&serach&list&trade on Taikos Network

Milestone2, 20 December 2023

- [ ] Support customized AIGC  creation  when minting NFTs
- [ ] Support good user experience with NFT Market 

### Project Plan

We will build the largest AI&NFT Dapp on Taiko Network, we will build an opensea-like NFT market, and will use AIGC(text2img, text2voice) to help users to mint NFTs

### Project Impact

By integrating AIGC(text2img, text2voice) technology, it helps users to better mint NFT with AI,  and through the establishment of an NFT trading platform, it helps users on the taiko network to trade NFTs.

### Team Information

Stay: CMO

-8 years of experience of web3 market

Richard: Core Developer

-5 years of experience of Blockchain development

Alex: Web-front Developer

-3 years of experience of Web-front

Spark: Designer

-5 years of experience of UI&UX

### Point of Contact

tg: staying08 | dicord: stay#5031 | email: bd@pizzap.io

### Previous Work

We have developed a simple AI&NFT website, users can mint, list, trade NFTs on taikos, and has been successfully submitted to Taiko Ecosystem project with [an issue](https://github.com/taikoxyz/taiko-mono/issues/14362)

### Agreement

- [X] I agree to comply with the terms and conditions of the grants program
